#!/usr/bin/python2.5

import osso
import gobject
import sys

def main():
    osso_c = osso.Context("osso_test_note", "0.0.1", False)
    note = osso.SystemNote(osso_c)
    result = note.system_note_infoprint(sys.argv[1])
#    print result

if __name__ == "__main__":
    main()
